### ISSUE TITLE
macOS?

### ISSUE THREAD

**Issue by aehlke** [Kyome22/EmojiPalette#1]

**Comment by Kyome22** [comment]
@aehlke 
Does that mean you want something for macOS?
If so, there is an official API, so use it.
[orderFrontCharacterPalette(_:)](https://developer.apple.com/documentation/appkit/nsapplication/1428455-orderfrontcharacterpalette)

**Comment by aehlke** [comment]
Oh great, thank you. It'd be nicest to have a unified SwiftUI interface to this + an iOS implementation, but it's easy enough to do myself now that I know about the macOS one, appreciate that
